version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
  logstash:
    image: logstash:7.4.2
    volumes:
      - ./logstash/config:/config      
    command: logstash -f /config/logstash.conf
  kibana:
    image: kibana:7.4.2
    ports:
      - 5601:5601

networks:
  default:
    external:
      name: netop-live-guide-realm
